[package]
name = "aoc2023"
version = "0.1.0"
authors = ["Thomas Kendrick <tom@tkendrick.com>"]
edition = "2021"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"

[[bin]]
name = "day3"
path = "src/day3.rs"
